### ISSUE TITLE
Bolivia doesn't have the detail crest (like defined in the wiki)

### ISSUE THREAD

**Issue by Danny-Engelman** [cedmax/flags#4]
![image](https://user-images.githubusercontent.com/3382713/60685190-022e7380-9ea2-11e9-9c54-efb5799da68b.png)

**Comment by cedmax** [comment]
Wow, thanks. Wiki data is really inconsistent: the page I took the data from didn't have the crest https://en.m.wikipedia.org/wiki/Gallery_of_sovereign_state_flags

**Comment by Danny-Engelman** [comment]
I think I have seen every flag on every site now. And every one has issues.

[http://flag-icon-css.lip.is/](http://flag-icon-css.lip.is/) is by far the most popular one.. BUT.. almost all his colors are wrong and his SVG is bloated with weird opacity rules and transforms to force them into 640x480

Your UI is the best

I am now recreating all flags (by hand) so JavaScript generates the SVG

Bolivia should become something like:

````
ad: stripes('#d52b1e', '#f9e300', '#007934') + detail('ad'); // lazy load detail
````

China:

````
cn:background('#de2910') +
            stars('#ffde00', [
                [5,        0, 8],
                [140,  30, 2.5, 30],
                [120,  75, 2.5],
                [120,  35, 2.5],
                [100,-50, 2.5, 30]
            ])
````

Takes some elbow grease...

**Comment by cedmax** [comment]
I can probably work on that, leave it with me. You mind opening a separate issue for that please?

**Comment by cedmax** [comment]
fixed
