### ISSUE TITLE
In the all flags UI Tanzania is missing a clip-path?

### ISSUE THREAD

**Issue by Danny-Engelman** [cedmax/flags#5]
The flags SVG itself is correct: https://flags.dsgn.it/static/media/tanzania.3824b05e.svg

But the UI shows:

![image](https://user-images.githubusercontent.com/3382713/60703370-ea86d780-9f01-11e9-8967-0fbbdc5c6428.png)

**Comment by cedmax** [comment]
Nice spot, thanks

**Comment by cedmax** [comment]
fixed
