### ISSUE TITLE
Access SVG URIs by ISO code

### ISSUE THREAD

**Issue by Danny-Engelman** [cedmax/flags#6]
It would be great if both your site and github repo could be accessed by **ISO code** only:

for example:

https://raw.githubusercontent.com/hjnilsson/country-flags/master/svg/bo.svg

https://lipis.github.io/flag-icon-css/flags/4x3/bo.svg

**Comment by cedmax** [comment]
there you go: https://flags.dsgn.it/assets/bo.svg

here's the list of the available iso codes: https://github.com/cedmax/flags/blob/master/modules/iso.json

**Comment by cedmax** [comment]
and thanks again for all the QA :)

**Comment by Danny-Engelman** [comment]
alas .. CORS.. so external domains are not allowed to load your files.

![image](https://user-images.githubusercontent.com/3382713/60767554-f74e2b80-a0b9-11e9-8165-729baddbe9f8.png)

Easiest is to dump all flags in a GitHub directory

**Comment by cedmax** [comment]
Sorry I must not have understood correctly the use case, I thought you wanted an easy way to fetch them, not to load them dynamically on other websites. I wouldn't do that tbh: right now the host is netlify but if I wad to move it the cost of the bandwidth wouldn't really be sustainable. Feel free to either script the download given the iso list or to fork the repo and do whatever needed: I can't rename all the files as my system works off ids that are deducted from the names of the countries and not all the countries I cover have an iso code assigned (I'm thinking at Abkhazia and such)

**Comment by Danny-Engelman** [comment]
I will get back to you later this week with the link to FlagMeister

Yes bandwidth is an issue, that is why I load all the other flags from the github repos:

* https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/as.svg
* https://raw.githubusercontent.com/hjnilsson/country-flags/master/svg/as.svg
* https://raw.githubusercontent.com/kent1D/svg-flags/master/flags/as.svg

This returns content-type:text to prevent hotlinking, but I want text as I inject it into other SVG content.

To be clear; **I** don't need your flags, (I have recreated all flags so JS generates the SVG)

FlagMeister is a site where people can pick the flags they want.

Or.. for you .. to compare your flags to others.

**Comment by cedmax** [comment]
Oh, ok, gotcha. I don't think I can provide that. As I mentioned I load them with a generates slug, not via iso code and changing it is not an option (too much refactoring involved). At the same time duplicating them would a problem as well, I would definitely forget to change both versions if I had an update. If you provide me the url I can probably look into enabling CORS to that domain only... Maybe that would do

**Comment by Danny-Engelman** [comment]
I said I would publish a link in a week... turned to a month.

https://flagmeister.github.io/

Is a 23 KB (gzip) Custom Element/WebComponent generating 300+ flags

https://flagmeister.github.io/documentation.html?flag=gb

is the direct link to the overview of Repos I can show the flag of  
**if the link is to a 2 letter (lowercase) iso code SVG flag**
